name: cd
on:
    push:
        branches: ["main"]

jobs:
    build-and-deploys:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Docker login
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PAT }}

            - name: Docker build and push
              uses: docker/build-push-action@v4
              with:
                  context: .
                  file: Dockerfile
                  push: true
                  tags: saatvik10/k8s-e2e:${{ github.sha }}
            
            - name: Cloning the repo, updating the image and pushing tags
              env:
                PAT: ${{ secrets.PAT }}
              run: |
                git clone https://github.com/saatvik-10/k8s.git
                cd k8s

                sed -i 's|image: saatvik10/k8s-e2e:*|image: saatvik10/k8s-e2e:${{ github.sha }}|' manifest.yml

                git config user.name "Github Actions Bot"
                git config user.email "actions@github.com"
                git add .
                git commit -m "updated k8s server image tags to ${{ github.sha }}"
                git push https://${PAT}@github.com/saatvik-10/k8s.git main